import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./Context/CartContext";
import { AddressProvider } from "./Context/AddressContext";
import { TokenProvider } from "./Context/TokenContext";
import { CurrentUserProvider } from "./Context/CurrentUserContext";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <AddressProvider>
            <CartProvider>
              <TokenProvider>
                <CurrentUserProvider>
                  {children}
                </CurrentUserProvider>
              </TokenProvider>
            </CartProvider>
          </AddressProvider>
      </body>
    </html>
  );
}
